[package]
name = "auth_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { workspace = true }
serde = { workspace = true }
email_address = { workspace = true }
snafu = { workspace = true, features = ["alloc"] }
